####################################################
##                                                ##
##                  qEssentials                   ##
##                 Configuration                  ##
##                                                ##
####################################################
# Messages language. 
# Available: pl, en, de
language: pl
# Help page length (commands per page)
help-page-length: 10
# Quit/Join formats
quit-format: '&c{PLAYER} left the game.'
join-format: '&a{PLAYER} joined the game.'
# Kick temporary ban in seconds
kick-temporary-ban: 20
####################################################
##                    Helpop                      ##
####################################################
helpop-delay: 10

####################################################
##                  Teleporting                   ##
####################################################
# Delay after command execute. In seconds.
delay: 10

####################################################
##                     Homes                      ##
####################################################
# Maximum amount of homes
max-homes: 3

####################################################
##                     Chat                       ##
####################################################
# Default chat format
chat-format: "&7{PLAYER}&8: &f{MESSAGE}"
# Chat slowdown (in seconds)
chat-slowdown: 3

####################################################
##                     Kits                       ##
####################################################
kits:
  start:
    cooldown: 20
    items:
      - 'cooked_beef 64 &cJedzonko'
      - 'stone_sword 1'

####################################################
##                  AutoMessage                   ##
####################################################
# delay between messages in seconds
automessage-delay: 35
# messages
automessages:
  - '&aWiadomosc 1'
  - '&bWiadomosc 2'
  - '&cWiadomosc 3'
  
# End of file -> Seriously... stop, this is stupid.
